site_name: wallabag documentation
theme: readthedocs
repo_url: http://github.com/wallabag/documentation
site_url: http://doc.wallabag.org/

site_description: wallabag documentation

pages:
- Home: index.md
